kit:
economy:
    enabled: false
    win: 2.5
    lose: -2.5
    draw: 1
prefix-enabled: true
metrics: true
update-check: true
offline-kick-time: 30
group-chat:
    enabled: true
    sign: '#'
    format: '%gc>ยง7%displayname: %message'