name: WarGear
version: ${project.build.version}
description: Postremus Wargear Fight Plugin
website: http://dev.bukkit.org/bukkit-plugins/wargear-fight/
author: postremus
main: WarGear
depend: [WorldEdit, WorldGuard, KitAPI]
soft-depend: [Vault, AdminCmd, Essentials, CommandBook]