wgk:
    defaults:
        arena: wgarena_1
    arenas:
        wgarena_1:
            world:
            arenaRegion:
            mode: kit
            groundHeight:
            regions:
                Team1:
                Team2:
            warpFightStart:
                Team1:
                    x:
                    y:
                    z:
                Team2:
                    x:
                    y:
                    z:
            warpFightEnd:
                x:
                y:
                z: