general:
    kit:
    economy:
        enabled: false
        win: 2.5
        lose: -2.5
        draw: 1
    enable-prefix: true
arenas:
    wgarena_1:
        world:
        mode: kit
        auto-reset: true
        water-remove: true
        team1-color: &c
        team2-color: &1
        scoreboard:
            enabled: true
            time: 30
        ground:
            height: 4
            schematic:
            damage: 4
        regions:
            team1:
            team2:
            arena:
        fightStart:
            team1: x;y;z
            team2: x;y;z
        fightEnd: x;y;z