name: WarGear
version: 0.8.4
description: Postremus Wargear Fight Plugin
website: http://dev.bukkit.org/bukkit-plugins/wargear-fight/
author: postremus
main: me.Postremus.WarGear.WarGear
depend: [WorldEdit, WorldGuard]