name: WarGear
version: 0.5.0
description: Postremus Wargear Arena Plugin
website: http://dev.bukkit.org/bukkit-plugins/wargear-fight/
author: postremus
main: me.Postremus.WarGear.WarGear
depend: [WorldGuard]

commands:
  wgk:
    description: Startet/Stoppt einen Fight
    usage: /wgk setup
    permission: wgk.wargear
    permission-message: 'Dazu fehlt dir die Berechtigung!'