name: WarGear
version: 0.7.0
description: Postremus Wargear Arena Plugin
website: http://dev.bukkit.org/bukkit-plugins/wargear-fight/
author: postremus
main: me.Postremus.WarGear.WarGear
depend: [WorldGuard]

commands:
  wgk:
    description: Alle Commands dieses Plugins
    usage: /wgk subcommand