name: WarGear
version: 0.4.0
description: Postremus Wargear Arena Plugin
website: http://www.bukkit.org
author: postremus
main: me.Postremus.WarGear.WarGear

commands:
  wgk:
    description: Startet/Stoppt einen Fight
    usage: /wgk setup
    permission: wgk.wargear
    permission-message: 'Dazu fehlt dir die Berechtigung!'