name: WarGear
version: 0.9-dev
description: Postremus Wargear Fight Plugin
website: http://dev.bukkit.org/bukkit-plugins/wargear-fight/
author: postremus
main: de.hrc_gaming.wg.WarGear
depend: [WorldEdit, WorldGuard]
soft-depend: [Vault]